apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-recreate
  labels:
    app: nginx-recreate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-recreate
  strategy:
    type: Recreate # terminate old Pods first, then create new Pods
  template:
    metadata:
      labels:
        app: nginx-recreate
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
