apiVersion: v1
kind: LimitRange
metadata:
  name: container-resource-policy
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m" # Used if a container request is omitted
        memory: "128Mi"
      default:
        cpu: "300m" # Used if a container limit is omitted
        memory: "256Mi"
      min:
        cpu: "50m" # Lower bound allowed per container
        memory: "64Mi"
      max:
        cpu: "1"
        memory: "512Mi"
      maxLimitRequestRatio:
        cpu: "4" # limit/request ratio cap for CPU
        memory: "2" # limit/request ratio cap for memory
